### ISSUE TITLE
Banner text on home page

### ISSUE THREAD

**Issue by lottebelice** [beeldengeluid/benglabs#1]
The banner text is now:

Welcome to LABS
EXPERIMENT WITH OUR APPLICATIONS, DATASETS AND API'S
DEVELOPED BY THE NETHERLANDS INSTITUTE FOR SOUND AND VISION

This does not convey the most relevant info and it's a lot of text in a big banner. How about:
Sound and Vision R&D Labs
APPLICATIONS, DATASETS AND API'S
DEVELOPED BY THE NETHERLANDS INSTITUTE FOR SOUND AND VISION

**Comment by jblom** [comment]
changed the text according to your suggestion
