### ISSUE TITLE
bug in CMS field contact person

### ISSUE THREAD

**Issue by evelienw** [beeldengeluid/benglabs#13]
There seems to be a bug in the CMS field for contact person (in datasets in this case). The email address and name are switched somehow, causing problems when clicking the field on the website. 

It's also not possible to edit a contact person by double clicking it (as stated above the field).

**Comment by jblom** [comment]
Ok I'll have a look tomorrow

**Comment by jblom** [comment]
Hi Evelien, this bug should be solved now
