### ISSUE TITLE
Adjust fields in CMS applications

### ISSUE THREAD

**Issue by evelienw** [beeldengeluid/benglabs#21]
Change te following fields in the CMS for adding applications:

1. (first) description field: change title to 'abstract'
2. add 'request authentication' field below 'access' field: should contain field for name, e-mail and organisation (as in contact details). Also show this on frontend.
3. add 'main topics' field: used for tags (seperate by semicolons) and show on frontend.
4. change type of content' to 'media type'
5. make 'poster' and 'thumbnail' list alphabetically

**Comment by jblom** [comment]
solved
