### ISSUE TITLE
Adjust fields in CMS apis

### ISSUE THREAD

**Issue by evelienw** [beeldengeluid/benglabs#23]
Change te following fields in the CMS for adding apis:

1. (first) description field: change title to 'abstract'
2. change the name of the 'info' field to 'specs', also on frontend
3. remove the 'additional info' field from the CMS
4. add 'main topics' field: used for tags (seperate by semicolons) and show on frontend
5. change 'tags' to 'media type' (seperate by semicolons)
6. make 'thumbnail' list alphabetically

**Comment by jblom** [comment]
solved
