### ISSUE TITLE
Tekst About aanpassen

### ISSUE THREAD

**Issue by Carlien** [beeldengeluid/benglabs#25]
Hoi Jaap,

Kun jij de huidige tekst bij "About" vervangen voor:

What about Sound and Vision?

The Netherlands Institute for Sound and Vision is an advanced and trendsetting audiovisual archive that has successfully made its way into the digital realm. It maintains and provides access to over 1 million hours of television, radio, music, film and web video, making it one of the largest audiovisual archives in Europe. Sound and Vision makes their collection available online for various end-user services, including dedicated services for the creative industries, education and research. The institute operates as a visitor attraction aimed at the general public and is visited by over 250.000 people annually.

The R&D department initiates research and develops programmes to make audiovisual heritage open and searchable. It follows relevant innovations in audio-visual archiving closely by participating in national and international research projects, by building a network of experts and gathering experience with new technologies.

The R&D research agenda focusses on five main themes: Access, Use and Context; Metadata; Users; Humanities; Digitisation and Preservation.

Read about the activities of Sound and Vision's R&D department on our blog or follow us on Twitter via @benglabs

For more information about Sound and Vision R&D, please contact: rd@beeldengeluid.nl

**Comment by jblom** [comment]
Hoi Carlien,

ik ga het dadelijk aanpassen!

J

**Comment by Carlien** [comment]
Thanks!

**Comment by jblom** [comment]
done!
