### ISSUE TITLE
Uploaden publicaties werkt niet in cms. Hi Jaap, ik probeer een publicatie te uploaden bij applicatie AVResearcherXL en dat lukt niet. Hij wordt niet toegevoegd, kun jij hiernaar kijken?

### ISSUE THREAD

**Issue by Carlien** [beeldengeluid/benglabs#26]

**Comment by jblom** [comment]
ik ga het fixen maar: als je i.p.v. dubbelklikken op een lege tabel het +'je gebruikt zou die iig wel de data in de tabel moeten opslaan. Klopt dat?

**Comment by jblom** [comment]
ok dit is gefixed. Je ziet nu ook de blogs + publicaties op de applicatie pagina
