### ISSUE TITLE
bijvoegen twee plaatjes op de links pagina voor Floss en GTAA en aanpassen tekst

### ISSUE THREAD

**Issue by Carlien** [beeldengeluid/benglabs#27]
Hoi Jaap,

Ik kan de links pagina niet aanpassen. Stuur je de plaatjes en tekst via de mail.

**Comment by jblom** [comment]
ok, ik ben hier nog 20 minuten

**Comment by Carlien** [comment]
Super super Jaap! Fijn dat publicaties gefixt is. Thanx;-)

Een hartelijke groet,

*Carlien Booij*

Projectleider Digital Humanities

*T* 035 - 677 3850
*M* 06 - 47400577

*Aanwezig:* ma, di, do, vr

Nederlands Instituut voor Beeld en Geluid
Media Parkboulevard 1, 1217 WE Hilversum

Postbus 1060, 1200 BB, Hilversum
www.beeldengeluid.nl
<http://www.google.com/url?q=http%3A%2F%2Fwww.beeldengeluid.nl%2F&sa=D&sntz=1&usg=AFrqEzeYY4n4jf6_kMuxEiAUu6jGk81HxA>
<http://www.google.com/url?q=http%3A%2F%2Ffiles.beeldengeluid.nl%2Fhandtekening%2Findex.html&sa=D&sntz=1&usg=AFrqEzf9le-GPxjM_7xHGHcDxr_nNJAmJg>


2015-05-05 16:40 GMT+02:00 Jaap Blom <notifications@github.com>:

**Comment by jblom** [comment]
de link tekstjes heb ik nu aangepast. Er zit inderdaad een eigenaardigheidje in waardoor je soms niet goed kan editen in de admin. Kom ik wel eens laten zien en later poog ik het eens op te lossen

**Comment by Carlien** [comment]
Hoi Jaap, nu het erin staat zie ik dat dit niet zo mooi is, kan dit nog binnen de 20 minute?? 

For the convenience of the GLAM community we have compiled a list of Free/Libre and Open Source Software. To contribute to the FLOSS inventory, email Gregory Markus (gmarkus@beeldengeluid.nl)

vervangen door:

For the convenience of the GLAM community we have compiled a list of Free/Libre and Open Source Software. To contribute to the FLOSS inventory, email Gregory Markus at:  gmarkus@beeldengeluid.nl
