### ISSUE TITLE
Navigation / interaction with main category icons unclear

### ISSUE THREAD

**Issue by lottebelice** [beeldengeluid/benglabs#4]
When I select either the APIs, Datasets or Applications icons, I don't get any feedback on what happened. I have to scroll down to see that I've actually filtered out some things. Maybe when a user clicks an icon, the big banner bar should move up, and the icons move to the top of the screen, also displaying the filtered results? Also, might be good to indicate that that specific filter icon is active.

**Comment by jblom** [comment]
yes this is my main issue with the whole site. Hope to find a nice solution.

**Comment by jblom** [comment]
now it jumps just above the header of the selected option, e.g. EXPERIMENT WITH ONE OF OUR AVAILABLE DATASETS after you have selected the datasets option.
