### ISSUE TITLE
Text: TRY OUT THE VARIOUS APPLICATIONS WE HAVE CREATED WITH OUR PARTNERS

### ISSUE THREAD

**Issue by lottebelice** [beeldengeluid/benglabs#5]
Not sure about "TRY OUT THE VARIOUS APPLICATIONS WE HAVE CREATED WITH OUR PARTNERS" on the home page. It's long and somewhat off language-wise. Also, it's not just about applications, but about datasets and APIs as well and thus it repeats what is already in the banner text.

Suggestion: remove it.

**Comment by jblom** [comment]
removed it
