### ISSUE TITLE
Blocks with datasets/apps/apis: indicate category

### ISSUE THREAD

**Issue by lottebelice** [beeldengeluid/benglabs#8]
In the blocks below the categories, you see the various datasets/apps/apis. I'd indicate in each blocks which category it belongs to. e.g. DIVE is an application, Open Images is a dataset (and API?).

**Comment by jblom** [comment]
I added icons to each block. (the same icons used for the main selection of application, dataset, api. (Openbeelden is both an app and an API, but link to different pages with different information, I'll see if I can interlink these two pages)
